# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecfg < Formula
  desc "A fast, secure CLI tool for managing Kubernetes kubeconfig files"
  homepage "https://github.com/kadirbelkuyu/kubecfg"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.1.6/kubecfg_0.1.6_darwin_amd64.tar.gz"
      sha256 "b1727ddf4437c2308683b16842221fb9587503c8a82d846a0baebbbdaa3ef8a5"

      define_method(:install) do
        bin.install "kubecfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.1.6/kubecfg_0.1.6_darwin_arm64.tar.gz"
      sha256 "09ae3a56d6c4611edbf2a11109f8670260132fcbd8f1ccc5882e278e64102378"

      define_method(:install) do
        bin.install "kubecfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.1.6/kubecfg_0.1.6_linux_amd64.tar.gz"
      sha256 "b682fff759b44c8a3cefcb09bf17aea05725a33dbda8b5e5aea5fde86cc8a451"
      define_method(:install) do
        bin.install "kubecfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.1.6/kubecfg_0.1.6_linux_arm64.tar.gz"
      sha256 "2030c443df41fd8f50a0a9276d3328a7a0d02e8f2598a6dc88dd539b5b85d5cf"
      define_method(:install) do
        bin.install "kubecfg"
      end
    end
  end

  test do
    system "#{bin}/kubecfg", "--help"
  end
end
