# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecfg < Formula
  desc "A fast, secure CLI tool for managing Kubernetes kubeconfig files"
  homepage "https://github.com/kadirbelkuyu/kubecfg"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.0.4/kubecfg_0.0.4_darwin_amd64.tar.gz"
      sha256 "771ed123b147e9fa38981deb0c3d8d09fef8f7101d6a8704267a84620075d1fc"

      def install
        bin.install "kubecfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.0.4/kubecfg_0.0.4_darwin_arm64.tar.gz"
      sha256 "cf4bda514935d6d528d51474adf4f0cccc4fd14b15cc1f16a1b9e5eeb79633e1"

      def install
        bin.install "kubecfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.0.4/kubecfg_0.0.4_linux_amd64.tar.gz"
      sha256 "d4289d0113ff7b83baef8bf2737ed527f319b6fae9802b9f844d8594efee29de"
      def install
        bin.install "kubecfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.0.4/kubecfg_0.0.4_linux_arm64.tar.gz"
      sha256 "1e64618095de054e06e33f9159110903c1941fbe2461b1ab7766d6fbb85378a9"
      def install
        bin.install "kubecfg"
      end
    end
  end

  test do
    system "#{bin}/kubecfg", "--help"
  end
end
