# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecfg < Formula
  desc "A fast, secure CLI tool for managing Kubernetes kubeconfig files"
  homepage "https://github.com/kadirbelkuyu/kubecfg"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.1.2/kubecfg_0.1.2_darwin_amd64.tar.gz"
      sha256 "821750eb3aba1890b105bea3bebf3f0a54310d669ee0303022ec019f7b887ca8"

      def install
        bin.install "kubecfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.1.2/kubecfg_0.1.2_darwin_arm64.tar.gz"
      sha256 "5b05eebea87653bdc9fd278f9a54fcd13496dd725168d04cb40ebd03f289bea0"

      def install
        bin.install "kubecfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.1.2/kubecfg_0.1.2_linux_amd64.tar.gz"
      sha256 "d124aa6d0df118c221647d66c723cb81d54af7bbbd58ceccdb2833a9fffa73dd"
      def install
        bin.install "kubecfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.1.2/kubecfg_0.1.2_linux_arm64.tar.gz"
      sha256 "84187ecc7c00b64303098e1b989c0a69f8366fca09296a8d04ce00e7f12af325"
      def install
        bin.install "kubecfg"
      end
    end
  end

  test do
    system "#{bin}/kubecfg", "--help"
  end
end
