# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecfg < Formula
  desc "A fast, secure CLI tool for managing Kubernetes kubeconfig files"
  homepage "https://github.com/kadirbelkuyu/kubecfg"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.0.2/kubecfg_0.0.2_darwin_amd64.tar.gz"
      sha256 "e8367db4161033f200dd42093d3b77094b6336a8db7eb0eeb69a4a80bb026f8e"

      def install
        bin.install "kubecfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.0.2/kubecfg_0.0.2_darwin_arm64.tar.gz"
      sha256 "b5730e59f188ced47456dd2157697a8dd3326218a7c2536b5fb8625e76ed80b9"

      def install
        bin.install "kubecfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.0.2/kubecfg_0.0.2_linux_amd64.tar.gz"
      sha256 "827c182c1cede7dd0f7e90e5a7182665368688f416f27dee62f28ecf5032fbcd"
      def install
        bin.install "kubecfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kadirbelkuyu/kubecfg/releases/download/v0.0.2/kubecfg_0.0.2_linux_arm64.tar.gz"
      sha256 "e6538dad9a8b6c8dffc0e09725a7e36e8046815956b0cd22920056d296fc7c8c"
      def install
        bin.install "kubecfg"
      end
    end
  end

  test do
    system "#{bin}/kubecfg", "--help"
  end
end
